/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PART_C_H_RPCGEN
#define _PART_C_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numbers {
	int a;
	int b;
	char *path;
};
typedef struct numbers numbers;

#define MY_PROG 0x12345678
#define MY_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define add 1
extern  char ** add_1(numbers *, CLIENT *);
extern  char ** add_1_svc(numbers *, struct svc_req *);
extern int my_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);
extern char *logger_ip;
extern int portno;
#else /* K&R C */
#define add 1
extern  char ** add_1();
extern  char ** add_1_svc();
extern int my_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numbers (XDR *, numbers*);

#else /* K&R C */
extern bool_t xdr_numbers ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PART_C_H_RPCGEN */
